//! Safety guard for preventing hallucination and tagging claim sources

use crate::{AiAnalystError, AiResult};
use serde::{Deserialize, Serialize};

/// Source of a claim in AI analysis
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ClaimSource {
    /// Evidence directly from scanner findings
    Evidence,
    /// Interpretation/analysis generated by AI
    Interpretation,
    /// Uncertain - model explicitly states uncertainty
    Uncertain { reason: String },
}

/// A claim with source tagging
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaggedClaim {
    /// The claim content
    pub content: String,

    /// Source of the claim
    pub source: ClaimSource,

    /// Confidence level (0.0 - 1.0)
    pub confidence: Option<f32>,

    /// Reference to supporting evidence (if Evidence source)
    pub evidence_reference: Option<String>,
}

/// Safety guard for AI responses
pub struct SafetyGuard {
    /// Whether to enforce strict evidence grounding
    strict_evidence_checking: bool,
}

impl SafetyGuard {
    /// Create a new safety guard
    pub fn new(strict_evidence_checking: bool) -> Self {
        Self {
            strict_evidence_checking,
        }
    }

    /// Tag claims in a response with their sources
    pub fn tag_claims(&self, content: &str, evidence_ids: &[String]) -> Vec<TaggedClaim> {
        // This is a simplified implementation - in practice, this would use more sophisticated NLP
        // to identify specific claims and match them to evidence

        let mut claims = Vec::new();

        // For now, we'll treat the entire content as one claim
        // In a real implementation, we'd break it down into individual assertions
        claims.push(TaggedClaim {
            content: content.to_string(),
            source: ClaimSource::Interpretation,
            confidence: None,
            evidence_reference: None,
        });

        claims
    }

    /// Validate that AI response only references actual findings
    pub fn validate_response_grounding(
        &self,
        response: &str,
        available_finding_ids: &[String],
    ) -> AiResult<()> {
        if !self.strict_evidence_checking {
            return Ok(());
        }

        // Simple validation - check for finding ID references that don't exist
        // This is a basic implementation - a real one would be more sophisticated
        for mentioned_id in self.extract_mentioned_finding_ids(response) {
            if !available_finding_ids.contains(&mentioned_id) {
                return Err(AiAnalystError::SafetyViolation(format!(
                    "AI response references finding ID '{}' which was not provided in context",
                    mentioned_id
                )));
            }
        }

        Ok(())
    }

    /// Extract finding IDs mentioned in text (simplified)
    fn extract_mentioned_finding_ids(&self, text: &str) -> Vec<String> {
        // This is a very basic implementation - would need proper regex/NLP in practice
        let mut ids = Vec::new();

        // Look for UUID-like patterns that might be finding IDs
        // This is just a placeholder - real implementation would be more robust
        use regex::Regex;
        if let Ok(re) = Regex::new(
            r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        ) {
            for cap in re.captures_iter(text) {
                ids.push(cap[0].to_string());
            }
        }

        ids
    }

    /// Process structured response to ensure evidence grounding
    pub fn process_structured_response<T>(
        &self,
        response: &T,
        available_finding_ids: &[String],
    ) -> AiResult<T>
    where
        T: serde::Serialize + serde::de::DeserializeOwned,
    {
        if !self.strict_evidence_checking {
            return Ok(response.clone());
        }

        // Convert to JSON and back to validate structure
        let json_str = serde_json::to_string(response)?;

        // Validate that no unknown finding IDs are referenced
        self.validate_response_grounding(&json_str, available_finding_ids)?;

        // Parse back to ensure it's still valid
        let processed: T = serde_json::from_str(&json_str)?;
        Ok(processed)
    }

    /// Add safety warnings to response if needed
    pub fn add_safety_warnings<T>(&self, response: &mut T, warnings: &[String]) -> AiResult<()>
    where
        T: serde::Serialize + serde::de::DeserializeOwned,
    {
        // This would modify the response to include safety warnings
        // For now, we'll just log that warnings should be added
        for warning in warnings {
            tracing::warn!("Safety warning: {}", warning);
        }

        Ok(())
    }

    /// Check if response contains hallucinated information
    pub fn detect_hallucination(&self, response: &str, context: &str) -> Vec<HallucinationAlert> {
        let mut alerts = Vec::new();

        // Check for claims not supported by context
        // This is a simplified implementation - real one would be more sophisticated

        // Look for absolute statements about impact/exploitability not in context
        if response.contains("will allow attackers to") && !context.contains("allow attackers") {
            alerts.push(HallucinationAlert {
                alert_type: HallucinationType::UnsubstantiatedImpact,
                description: "Response claims specific attack outcomes not supported by evidence"
                    .to_string(),
                confidence: 0.7,
            });
        }

        // Look for technology references not in context
        // This would need a more sophisticated implementation

        alerts
    }
}

/// Type of hallucination detected
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HallucinationType {
    UnsubstantiatedImpact,
    InventedTechnology,
    FalseCausality,
    UnsupportedRemediation,
}

/// Alert about potential hallucination
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HallucinationAlert {
    pub alert_type: HallucinationType,
    pub description: String,
    pub confidence: f32, // 0.0 - 1.0
}

impl Default for SafetyGuard {
    fn default() -> Self {
        Self::new(true) // Strict checking by default
    }
}

/// Wrapper for AI responses with safety metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafeResponse<T> {
    /// The actual response content
    pub content: T,

    /// Safety metadata
    pub safety_metadata: SafetyMetadata,

    /// Any warnings about the response
    pub warnings: Vec<String>,
}

/// Safety metadata for responses
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafetyMetadata {
    /// Whether all claims are grounded in evidence
    pub fully_groundedException: bool,

    /// List of tagged claims
    pub claims: Vec<TaggedClaim>,

    /// Any hallucination alerts
    pub hallucination_alerts: Vec<HallucinationAlert>,

    /// Model information
    pub model_info: Option<String>,

    /// Processing timestamp
    pub processed_at: chrono::DateTime<chrono::Utc>,
}
